### ISSUE TITLE
Check format we have to present results

### ISSUE THREAD

**Issue by EauDeData** [MCV-2022-M1-Project/Team7#9]
Idk if we should build a "results" interface or some module to save in disk results in the format we have to deliver

**Comment by ayanban011** [comment]
No, We need to save the mask of the test set provided by the professor on Sunday and retrieve the results in a .pkl file. Meanwhile, I think we need to start preparing the slides for the submission.

**Comment by ayanban011** [comment]
checked and solved!!!
